language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
  - "pypy"
before_install:
  # Update pip and setuptools to the latest.
  - pip install --upgrade pip setuptools
  - pip install codecov
install:
  # Install ipdb, which will install the right IPython version for the current python.
  - pip install -e .
script:
  - coverage run setup.py test
  - codecov
sudo: false

